"""
PlatformIO pre-build script: Replace ESPHome's default captive portal HTML
with our branded PlantHub WiFi setup page.

This script:
1. Reads captive_portal.html from firmware/common/
2. Gzip-compresses it
3. Generates a C header matching ESPHome's captive_index.h format
4. Overwrites src/esphome/components/captive_portal/captive_index.h
5. Adds -DUSE_CAPTIVE_PORTAL_GZIP build flag

Usage in base.yaml:
  esphome:
    platformio_options:
      extra_scripts:
        - pre:../../../../common/build_captive_portal.py
"""

import gzip
import os

Import("env")  # noqa: F821 — PlatformIO built-in


def generate_captive_index():
    # PROJECT_DIR = firmware/devices/.esphome/build/<device-name>/
    # Go up 4 levels to firmware/, then into common/
    project_dir = env.subst("$PROJECT_DIR")
    common_dir = os.path.normpath(
        os.path.join(project_dir, "..", "..", "..", "..", "common")
    )

    html_path = os.path.join(common_dir, "captive_portal.html")
    if not os.path.isfile(html_path):
        print(f"[captive_portal] WARNING: {html_path} not found, skipping")
        return

    # Target: the ESPHome-generated captive_index.h in the build src/
    src_dir = env.subst("$PROJECT_SRC_DIR")
    target_path = os.path.join(
        src_dir,
        "esphome",
        "components",
        "captive_portal",
        "captive_index.h",
    )
    if not os.path.isfile(target_path):
        print(f"[captive_portal] WARNING: {target_path} not found, skipping")
        return

    # Read and gzip our branded HTML
    with open(html_path, "rb") as f:
        html_bytes = f.read()

    compressed = gzip.compress(html_bytes, compresslevel=9)

    print(
        f"[captive_portal] Branded HTML: {len(html_bytes)} bytes "
        f"-> gzip: {len(compressed)} bytes"
    )

    # Format as C byte array (19 bytes per line to match ESPHome style)
    lines = []
    for i in range(0, len(compressed), 19):
        chunk = compressed[i : i + 19]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")

    # Remove trailing comma from last line (closing }; is in the template)
    if lines:
        lines[-1] = lines[-1].rstrip(",")

    byte_array = "\n".join(lines)

    # Generate the header file
    header = f"""#pragma once
// Generated by build_captive_portal.py — PlantHub branded captive portal

#include "esphome/core/hal.h"

namespace esphome::captive_portal {{

const uint8_t INDEX_GZ[] PROGMEM = {{
{byte_array}
}};

}}  // namespace esphome::captive_portal
"""

    with open(target_path, "w") as f:
        f.write(header)

    print(f"[captive_portal] Wrote {target_path} ({len(compressed)} bytes gzipped)")


# ESPHome already defines USE_CAPTIVE_PORTAL_GZIP in defines.h,
# so no need to add it via CPPDEFINES — just overwrite the header.

generate_captive_index()
